# .sops.yaml

keys:
  - &primary age1q75fpaup2fff4sad4e9shqhkp4cd6zdfdqdu6vm4p4mwe8gwq4wqmt9ede
  - &server_behemoth age10mwfapcjk0fly5hdz5s22ezsrflpx69kmvgcxapwk4qrl2xhcflq3efw3x
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *primary
      - *server_behemoth
